version: "3.0"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    depends_on:
      - mysql
    image: test-kubernetes:v1
    ports:
      - 8080:8080