apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    metadata:
      labels:
        name: app-pod
    spec:
        containers:
            - name: container-app
              image: masouza/app-test-kubernetes:v1
              ports:
                - containerPort: 8080