spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://mysql:3306/test_kubernetes?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
